### ISSUE TITLE
DNS Issues

### ISSUE THREAD

**Issue by Donkie** [GMDevinity/Flood#159]
We're having some DNS issues, possibly a DDoS against the DNS provider.
If you really want to use our devinity.org services you can temporarly fix it by adding this line in the Windows hosts file:
`63.251.20.163 devinity.org`

**Comment by bayrock** [comment]
Note to anyone who wants to change the Windows hosts file you'll need to open it in your text editor as an administrator. Otherwise it won't save your changes to the file.

**Comment by jeffreythe00** [comment]
I just drag it to the desktop where it doesn't need administrative permission.

Also this did not work for me.

**Comment by DrPitLazarus** [comment]
Does not work. Also putting 63.251.20.163 into the browser points to bayrock's page.

**Comment by bayrock** [comment]
@DrPitLazarus That's because the IP points to multiple pages. Not sure about details regarding that.

However, the DNS issues seemed to resolve itself now, and as an added precaution I've transferred our domain to a more reliable provider: http://f.bay.rocks/QUoTN

Hopefully this gives everyone a clear conscience.

**Comment by jeffreythe00** [comment]
Thanks Bay for doing what you can to help. ♡
