### ISSUE TITLE
Make a list of staff responisibilities

### ISSUE THREAD

**Issue by DecapX** [GMDevinity/Flood#38]
It has come up a few times where we can't really establish if we should demote someone because we cannot establish if they are doing thier jobs or if they only do things qualified for a different position. I think the best way to fix that is to make an established list of responsibilities and duties based on your staff position. Each position will carry those responsibilities onto the next tier if they are promoted up to Super Admin. However they must equally play out all or most of their duties to keep thier position. If they fall behind they could be demoted. In retrospect, we could see if lower tier staff are doing well in their jobs as well which could land them a promotion.

**Comment by DoctorSilver** [comment]
Ok, some personal things I believe in:

Super Admins-
-Be capable to be able to almost answer all question that come to you by lower staff or regular members (like 95% of them)
-Arrange community meetings (however often you feel, but probably at least once every two months)
-Deal with ban requests regarding staff member abuse/voteban abuse.
-Keep an eye on all staff to see that there's no abuse and everyone is staying active.
-Promote/demote staff depending on how well they're dealing with their tasks.
-Be in charge of staff applying for forum moderator, along with tracking how they're doing weather to be given more permissions or not.
-Moderate the forums.
-Moderate the servers and keep an eye on staff that are on probation.

Admins-
-Moderate the forums.  Deal with closing threads and moving them(player reports and ban requests wise, because moderators don't have any forum ability unless they got accepted for forum staff).
-Moderate the servers.
-Look for players you believe should be staff and give a heads up in the slack or just a pm on the forums.
-Help out and participate in who you believe should be staff and who shouldn't be, along with deciding who gets promoted and who doesn't.
-Take part and be decently active in the slack chat, it's really nice to be able to communicate easily with all admins+.
-Be active in the community as a whole, if anywhere is having problems (forums or servers) deal with it.  If you cannot, get a super admin or above to handle it for you.

Moderators-
-Take part in dealing with ban requests and ban appeals if you banned somebody.  You really do get the final say in most cases, unless upper staff have decided your ban was wrong/abusive.
-Moderate the servers, and I mean moderate servers not test out your cool new ban hammer.
-Apply for forum moderator (if you're down for that) and help out participating in forum discussions and group meetings.
-Moderate TeamSpeak3 (or whatever we're using by the time you read this).
-Be involved in who you think personally should be staff and who shouldn't be.
-Keep an eye on the junior moderators and help them with any questions they have.  And report all complete trouble makers on the forums for a super admin to deal with.

Junior Moderators-
-Moderate the servers with your ban new moderating powers.  If you have any questions ask any and all moderators and above.  Be very active as this is the only change in commands you obtain.
-Be involved in what is going on in the community as a whole, maybe the forums are not your thing, but at least try to come on them once a week to see how things are going.
-Apply for forum staff and moderate the forums if you get accepted.
-Help out your fellow junior moderators and report any abuse on the forums or directly to a super admin.
-Continue making ban requests for players you believe should be banned for more than an hour long.
-Don't completely vanish from the community just because you're a junior moderator, you need to stay active if you want to keep your rank+get promoted.

My list is not the greatest but it covers what it really needs to.

**Comment by Donkie** [comment]
Looks great, good job! 
Waiting for input from other members before making anything official about it

**Comment by RicksBeehive** [comment]
It's annoying because certain people are good at some things bad at others.

For example Alex moderates like a baws and is very good with players, but people like Laz contribute a tonne in other ways.

Could have less direct system at the top (Moderator- seems good). We've spoken before about having people with specific jobs doing specific things.

**Comment by DecapX** [comment]
Rick these duties will make it easier for everyone across the board. Instead of one person taking the load off of something, everyone contributes equally. It's also a great way to measure how much someone wants to contribute. Some want to help out with bigger things than just moderating. No one has made any complaints about it except you.

**Comment by RicksBeehive** [comment]
Decap that wasn't a compaint I was just talking about the way I've experienced it mate. It wasn't even negative to the threads topic overall?

I've always been an adovocate for giving people the opportunity to contribute to things beyond moderation and I've discussed that more than a year ago. I started the conversation on giving specific jobs to people well before the creation of this issue.

The idea at its core is very good, I love it in fact, but I never successfully came up with an sufficiently backed method to organise the idea properly. I'm sort of wondering how you'd go about doing it, would you just talk to them all individually?

People are very different and especially when it comes to the duties of an admin+, I'm not trying to rain on the parade I'm just curios because I directly brought this up ages ago and I want to see how it'll be done (Or is being done I have no idea)

**Comment by DecapX** [comment]
This isn't the final draft, the final one is posted in the Mod Forum. New staff will be tagged or linked to the thread and expected to follow the responsibilities. I agree that not all staff are good at certain things, however so far none have complained. I'm not wanting this to be a job per say, however I did want to set a bar minimum for what certain staff need to be doing. Maybe some will excel in one responsibility while another staff will do poorly but excel in another which I am ok with. There just needs to be something that says if you want to be a Jr. Mod, Mod, Admin, or Super Admin, you have to acknowledge that there are certain duties that you need to perform. If you can't perform these basic tasks then you simply aren't fit for staff or you need to get demoted to a position that better suits what you excel in. Like say we don't want an admin who simply plays the servers all day and that's it. On the flip side, maybe we have a Jr. Mod that has shown that he is better suited to being a mod or admin. Seeing these duties being performed by people gives me a measuring stick to see what they are capable of and how they measure up to others.

**Comment by Donkie** [comment]
Feels like this is pretty closeable?
