### ISSUE TITLE
Devinity Positioner Tool:  Utilizing elements from Bonemerger Tool for item attachment to model torsos

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#46]
When it comes to attaching certain props like vests onto a model's torso via the Bonemerger Tool, flexing is guaranteed to be exhibited and aesthetically looks appealing.  However, if attempts are made to rig a "flexible" item onto a model with the Devinitiy Positioner Tool, the attached item will remain stiff and visually shitty.

Whether it can be done through one way or another, could our tool be configured so that it would be able to execute prop-to-torso attachments in the way that Bonemerger can?

![rigging and flexing](https://cloud.githubusercontent.com/assets/16427724/14225187/723e8530-f86e-11e5-8935-8fc8af6b7830.png)

**Comment by Donkie** [comment]
I've looked into bonemerging and I spent several hours trying to figure it out. I've come to the conclusion that, yes it's possible to add, but due to the nature of bonemerging, the pos and angle sliders are broken, essentially meaning this won't be viable for the vast amount of different models we have.
