### ISSUE TITLE
Kick players when team slots go down + issue #19

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/Flood#76]
When team slots decrease, it should kick the team member that has recently joined to maintain balance only on build phase. (Other people will start to bitch if a team has 4/2)

Following issue #19, disallow players from making any teams when players are <7-9

**Comment by jeffreythe00** [comment]
I don't think this is a great idea as it would be frustrating to wait for a team slot to open up, then get kicked a few minutes later just because a few players left. I don't disagree that it _is unfair_ if there is a 3 person team who is winning majority of the time

**Comment by CounterCraftz** [comment]
If they just joined and a player leaves that makes team slots decrease, kick them until next round perhaps?

**Comment by Donkie** [comment]
Yeah the kicking would only take place after fight phase ends

**Comment by jeffreythe00** [comment]
This is how I see it happening.

Server gets 28 people.
A few 4 person teams are created
Round ends, and a few people rage quit (I notice some people will leave if they die or lose a lot)
Several people leave, breaking those 4 person teams down
Some people get upset because their team is reduced to 3
some more people leave
teams are further reduced
domino effect and the server goes empty

**Comment by CounterCraftz** [comment]
sucks to be them if all they whine about is that lol

**Comment by jeffreythe00** [comment]
The idea is that we want players to "play" the server so we can grow as a community. I wouldn't want to move away from that. 

Don't get me wrong. If you guys think this change will be for the better, I'll hop aboard with it but that doesn't mean I have to like it.

**Comment by Donkie** [comment]
Added this
