### ISSUE TITLE
Achievement Ideas

### ISSUE THREAD

**Issue by Donkie** [GMDevinity/Flood#8]
Please put in some achievement ideas here.

**Comment by jeffreythe00** [comment]
* Team player - Play with a team for 24 hours
* Gotta catch em all - Buy the Lucario skin
* Armed to the teeth - Buy all of the weapons
* Bill gates - Buy all playerskins

**Comment by DawsonDevinity** [comment]
Google document w/ numerous ideas:

https://docs.google.com/document/d/1-yg2aCll2qVxV_0mcJCb1uSCQ117D1x9kPsMrE8gNV8/edit

**Comment by Donkie** [comment]
@DawsonDevinity 
Remember that achievements can be unhidden once you've unlocked an achievement. Basically you can make like a "quest" with achievements, chaining them together. Also remember that we can reward anything when an achievement is unlocked. (hats, models, tokens, cash, weapons)

**Comment by DawsonDevinity** [comment]
Thanks!  Let me know if anything needs to be renamed or properly readjusted.
____________________________________________________

(1) Cool beans!  I try to generate some "mission" ideas for us.

(2) Way ahead of you on that.  For most of the achievement ideas I wanted to start off with getting their framework right before attaching rewards to them.

(3) Do you have any resource websites you could refer me to?  I'd like to try keeping incoming icon designs consistent with the ones currently in use.

**Comment by Donkie** [comment]
I mostly use Google and set image size to 32x32 and type to transparent. However there are several websites with icons you can steal from. If you want more generic and boring ones, icomoon is a good one.

**Comment by DawsonDevinity** [comment]
The first several images up to "Evaporation" have been created.  They should be viewable in the doc.  Let me know what you think.

**Comment by Donkie** [comment]
Still waiting for icons for these:

Ye Olde Pirate Ship
War Dinghy
Floating Fortress
Half-Way Raft
Death Insurance

**Comment by CounterCraftz** [comment]
General:

Hole in One!: Destroy 7 props with a single grenade in a single round.
A True Pirate: Destroy 3 props with a crowbar while wearing a pirate hat in a single round. 
Doctor Fanatic: Equip the 'amazing' apparel in the Token Shop. 
Doctor Plague - Toxicate 5 players with a bugbait. (I think the kill should be transferred instead of just plain suiciding in the kill feed.).
Unbelievable!: Win consistently of 5 rounds while there are more than 16 players.

Event:

Puzzle Piecer: Build your way up 3/4th of the map while in Build to the Top Event. (Without using noclip at all)
From the Caribbean: Build a boat with 2 essential equipment to set in the Sea. (Pirate Round)
Cause a Pirate is Free!: Kill 5 players with your crowbar on the Pirate Round. (Similar to Zombie Event Achivements)
*Winner Survival: Survive 10 rounds on the Zombie Event.
Unbelievable!: Win a constant 
Dodge this!: Win 3 rounds in the dodgeball event.
Can't touch this: Survive a round in the dodgeball event after you got hit by a missile.

most are copied from my thread but its fine

**Comment by Donkie** [comment]
Could do with some explaining for your achievements counter, "amazing apparel", "2 essential equipment"??

**Comment by CounterCraftz** [comment]
'Amazing' Apparel leads to wearing the kleiner player model.  2 essential equipment is boat mortar and the cannon.

**Comment by DawsonDevinity** [comment]
I apologize for the extended delay in producing icons.  I'll try to produce them over a period of several days.

**Comment by DawsonDevinity** [comment]
Got the icons made, Donkie.  It was much quicker than I anticipated.
